version: '2'

services:
  db:
    image: mariadb:10.1.11
    volumes:
      - "/var/lib/mysql"
      - "../mariadb/conf1:/etc/mysql/conf.d:ro"
      - "../../sql/:/docker-entrypoint-initdb.d:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=strong_pitchou
    ports:
      - "3306:3306"

  clamp:
    image: onap/clamp
    volumes:
      - "./config/:/opt/clamp/config:rw"
    depends_on:
      - db
    env_file:
      - clamp.env
    ports:
      - "8080:8080"

  sdc_proxy:
    image: python:2-slim
    volumes:
      - "../../../src/test/resources/http-cache/sdc-example/:/sdc:ro"
      - "../../../src/test/resources/http-cache/:/script/:ro"
    depends_on:
      - clamp
    ports:
      - "8085:8085"
    command: /bin/sh -c "pip install requests && python /script/sdc_proxy.py --port 8085 --root /sdc"
